apiVersion: v1
kind: ConfigMap
metadata:
  name: fortune-config
  namespace: default
data:  # kubectl create cm cm-fortune-config.yaml --from-file=configmap-files
   author: yz
  # sleep-interval: "25"
