# kubectl create -f deploy-kubia-deployment-v1.yaml --record
# 使用--record，可以记录历史版本号

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  selector:
    matchLabels:
      app: kubia
  replicas: 3
  revisionHistoryLimit: 3 # 保留replicaSet的版本数量
  minReadySeconds: 10 # 滚动升级时，10秒升级一次
  strategy:
    rollingUpdate:
      maxSurge: 1 # 最多允许超出pod数量
      maxUnavailable: 0 # 允许多少个pod不可用
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - name: nodejs
          image: yanzhen0/kubia:v1 # 触发滚动升级--> kubectl set image deploy kubia nodejs=yanzhen0/kubia:v2


---
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30123
  selector:
    app: kubia