apiVersion: v1
kind: Service
metadata:
  name: kubia-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true" # 没有准备好的pod也展示出来
spec:
  clusterIP: None # 不分配集群IP，成为无头集群
  ports:
  - name: http
    port: 7973
    targetPort: 8080
  selector:
    app: kubia
