apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v3
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux0
  containers:
  - image: yanzhen0/kubia
    name: kubia
    ports:
    - containerPort: 7878
      protocol: TCP