apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
  - image: yanzhen0/fortune
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    ports:
    - containerPort: 8282
      protocol: TCP
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 8181
      protocol: TCP
  volumes:
  - name: html
    emptyDir:
      medium: Memory #emptyDir的文件将会存储在内存中


