apiVersion: v1
kind: Pod
metadata:
  name: downward
  labels:
    foo: bar
  annotations:
    key1: value1
    key2: |
      multi
      line
      value
spec:
  containers:
    - name: main
      image: busybox
      command: ["sleep", "9999999"]
      resources:
        requests:
          cpu: 15m
          memory: 100Ki
        limits:
          cpu: 100m
          memory: 6Mi
      volumeMounts:
        - mountPath: /etc/downward
          name: downward # 在/etc/downward目录挂载downward卷
  volumes:
    - name: downward # downward卷
      downwardAPI:
        items:
          - path: "podName"
            fieldRef:
              fieldPath: metadata.name
          - path: "podNamespace"
            fieldRef:
              fieldPath: metadata.namespace
          - path: "labels" # 保存在 /etc/downward/labels 中
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations" # 保存在 /etc/downward/annotations 中
            fieldRef:
              fieldPath: metadata.annotations
          - path: "containerCpuRequestMilliCores"
            resourceFieldRef:
              resource: requests.cpu
              containerName: main
              divisor: 1m
          - path: "containerMemoryLimitBytes"
            resourceFieldRef:
              resource: limits.memory
              containerName: main
              divisor: 1Mi
