apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 8181
      protocol: TCP
  volumes:
  - name: html
    gitRepo: #gitRepo卷，git仓库挂在卷
      repository: https://github.com/I-want-to-knowledge/kubia-website-example.git # git仓库链接
      revision: master # 分支
      directory: . # 根目录
