apiVersion: v1
kind: Pod
metadata:
  name: fortune-env
spec:
  containers:
    - image: yanzhen0/fortune:env
      env:
        - name: FIRST_VAR
          value: "借用一下，"
        - name: INTERVAL
          value: "$(FIRST_VAR)假装一个环境变量"
      args:
        - "10" # 传递一个参数，设置日志2秒打印一次
      name: html-generator
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
      ports:
        - containerPort: 8282
          protocol: TCP
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      ports:
        - containerPort: 8181
          protocol: TCP
  volumes:
    - name: html
      emptyDir:
        medium: Memory #emptyDir的文件将会存储在内存中
