apiVersion: v1
kind: Pod
metadata:
  name: fortune-https
spec:
  containers:
    - image: yanzhen0/fortune:env
      env:                            # 传入整个configMap的键值，使用envFrom
        - name: INTERVAL
          valueFrom: # 用configMap初始化，不设定固定值
            configMapKeyRef:
              optional: true # configMap不存在时，尝试运行
              name: fortune-config # configMap名称
              key: sleep-interval # configMap对应的键值
      args:
        - "10" # 传递一个参数，设置日志10秒打印一次
      name: html-generator
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certs
          mountPath: /etc/nginx/certs/
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
  volumes:
    - name: html
      emptyDir: {}
    - name: config
      configMap:
        name: cm-fortune-config
        items:
          - key: my-nginx-config.conf
            path: https.conf
    - name: certs
      secret:
        secretName: fortune-https # 引用fortune-https secret定义券
