apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  #type: ExternalName
  #externalName: kubia
  ports:
  - name: http1
    port: 7977
    targetPort: 8080
  - name: http2
    port: 7976
    targetPort: 8080
  selector:
    app: kubia
