apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-reader # kubectl create clusterrole pv-reader --verb=get,list --resource=persistentvolumes
rules:
  - apiGroups:
      - ""
    resources: # 根据verbs值，可以查看和列表pv
      - persistentvolumes
    verbs: # get, list, create, update, patch, watch, delete, deletecollection
      - get
      - list
