apiVersion: v1
kind: Pod
metadata:
  namespace: foo
  name: curl-custom-sa
spec:
  serviceAccountName: foo # 可以直接执行命令：kubectl create sa foo
  containers:
#    - name: main
#      image: tutum/curl
#      command:
#        - sleep
#        - "9999999"
    - name: ambassador
      image: nginx:latest # ambassador容器，运行kubectl-proxy镜像
#      command:
#        - /bin/sh
#      args:
#        - -c
#        - /kubectl proxy --server="https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT" --certificate-authority="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --accept-paths='^.*'
#