apiVersion: v1
kind: LimitRange
metadata:
  name: example
spec:
  limits:
    - type: Pod # 指定整个pod的资源limits
      min: # pod中所有容器的CPU和内存请求量之和的最小值
        cpu: 50m
        memory: 5Mi
      max: # pod中所有容器的CPU和内存请求量之和的最大值
        cpu: '1'
        memory: 1Gi
    - type: Container # 指定容器的资源限制
      defaultRequest: # 容器没有设置CPU和memory时设置默认值
        cpu: 100m
        memory: 10Mi
      default: # 没有指定limits时设置的默认值
        cpu: 200m
        memory: 100Mi
      min: # 容器的cpu和memory最小值
        cpu: 50m
        memory: 5Mi
      max: # 容器的cpu和memory最大值
        cpu: '1'
        memory: 1Gi
      maxLimitRequestRatio: # 每种资源requests与limits的最大比值
        cpu: '4'  # requests.cpu * 4 <= limits.cpu
        memory: '10'  # requests.memory * 10 <= limits.memory
    - type: PersistentVolumeClaim # LimitRange指定请求PVC存储容量的最大值和最小值
      min:
        storage: 1Gi
      max:
        storage: 10Gi
