apiVersion: networking.k8s.io/v1
kind: NetworkPolicy # 隔离pod的网络
metadata:
  name: postgres-netpolicy
spec:
  podSelector: # 这个策略确保了对具有app=database标签的pod的访问安全性
    matchLabels:
      app: database
  ingress: # 只允许来自具有app=webserver标签的pod的访问
    - from:
        - podSelector:
            matchLabels:
              app: webserver
    - ports: # 允许对端口访问
        - port: 5432
