apiVersion: networking.k8s.io/v1
kind: NetworkPolicy # 隔离pod的网络
metadata:
  name: cicr-netpolicy
spec:
  podSelector: # 策略用于有app: shopping-cart标签的pod
    matchLabels:
      app: shopping-cart
  # 入向规则
  ingress: # 只允许来自具有tenant: manning标签的namespace的pod可以访问
    - from:
        - ipBlock: # 这条入向规则来自192.168.1.0/24段的客户段流量
            cidr: 192.168.1.0/24
    - ports: # 允许对端口访问
        - port: 80
  # 出向规则
  egress: # 限制pod的出流量
    - to: # 允许app: shopping-cart标签的pod访问具有标签app: database的pod（除此之外的任何pod不能访问任何地址，不管集群内部还是外部）
        - podSelector:
            matchLabels:
              app: database